### ISSUE TITLE
reverse "i want to receive emails" checkbox

### ISSUE THREAD

**Issue by jmrgibson** [missmaggiemo/mcs_registration#72]
The default behaviour is to have this checkbox *unchecked* with the text saying that you "Don't" want to receive emails.  I feel like it would make more sense to have the checkbox checked by default, and change the text to have it say the positive case, eg  "I wish to receive emails from MCS"  (no functional change, just a UI change)

@missmaggiemo thoughts?

**Comment by missmaggiemo** [comment]
So, originally, Eric wanted this check box to exactly mirror the written form, which has the Check-if-you-don't syntax. But I read this issue as saying that the community would like this to be different! So let's change it. My only request would be that the data coming out of the check box be compatible with the old data. Otherwise, we'll need to do some sort of a data migration.

**Comment by rkstedman** [comment]
@jmrgibson I like this suggestion because I think it is more typical for "email" checkboxes and more familiar/clearer to people. However, after looking into implementing it (https://github.com/missmaggiemo/mcs_registration/pull/91), I don't think the change is worth it. It adds some complexity if we want to avoid changing the data in the database. And we could change the data in the database of course but that would also be some effort.

Also when I talked to Maggie we realized that as far as we know, the MCS mailing list hasn't even been used? So for now at least, we wouldn't realize a tangible impact from improving this -- so closing out my PR for now.
